[jenkins_master]
13.232.127.209 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/apple/Downloads/devops-key.pem

[jenkins_node]
35.154.72.113 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/apple/Downloads/devops-key.pem

[app_docker]
43.205.156.246 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/apple/Downloads/devops-key.pem

[k8s_node]
52.66.40.100 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/apple/Downloads/devops-key.pem

[monitoring]
13.234.235.173 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/apple/Downloads/devops-key.pem
