---
- hosts: jenkins_master
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Ensure directory for keyrings exists
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository
      copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/\n"
        mode: '0644'

    - name: Update apt cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add Jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Enable and start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
