---
- hosts: k8s_node
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Create kube config directory for ubuntu
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0700'
        owner: ubuntu
        group: ubuntu

    - name: Copy k3s kubeconfig for ubuntu
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0600'
        remote_src: yes
